# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme
- jekyll-autolink_email

# Site settings
url: 'https://www.chaingrok.com'
baseurl: ''
title: 'ChainGrok (chaingrok@gmail.com)'
description: 'This is my new website'
permalink: pretty
logo: "https://www.chaingrok.com/img/chaingrok-thumbnail.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: home
  url: /
- title: about
  url: /about/
- title: blog
  url: /blog/
- title: chaingrok@gmail.com

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Blog
    output: true
    description: "Thoughts and ideas about blockchains (mostly ...) by [chaingrok@gmail.com](mailto:chaingrok@gmail.com)"
    feature_image: "https://www.chaingrok.com/img/chaingrok-header.png"
